version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"