version = 1

test_patterns = [
  "tests/**",
  "test_*.py",
  "*/test/**"
]

exclude_patterns = [
  "migrations/**",
  "**/examples/**",
  "*/public/**,",
  "*/dist/**",
  "*/docs/**"
]

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["./Dockerfile"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]
  cyclomatic_complexity_threshold = "very-high"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  cyclomatic_complexity_threshold = "high"

[[transformers]]
name = "prettier"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"
