[tool.black]
line-length = 79

[tool.isort]
known_first_party = ["predikit", "tests"]
default_section = "THIRDPARTY"
line_length = 79
profile = "black"
combine_as_imports = true
force_grid_wrap = 2
force_sort_within_sections = true
skip_glob = "env"