name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DATE: date +%s

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the backend Docker image
        run: docker build . --file Dockerfile --tag predikit:$DATE
      - name: Run the backend Docker image
        run: docker run -d -p 5001:5001 predikit:$DATE
      - name: Stop the backend Docker container
        run: docker stop $(docker ps -q --filter ancestor=predikit:$DATE)
